declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*..gif';
declare module '*.webp';
declare module '*.tiff';
declare module '*.mp4';
declare module 'react-dom/client';
